---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types:
      - completed

jobs:
  deploy-release:
    name: 👷 Deploy to Release
    if: |
      github.event_name == 'release'
      || (
        github.event_name == 'workflow_run'
        && github.event.workflow_run.conclusion == 'success'
      )
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: ⤵️ Download Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          name: build
          path: build
          workflow: ci.yml
          workflow_conclusion: success
      - name: 🏗 Compress directories
        run: |
          cd build
          tar -czvf frontend.tar.gz *
      - name: ⬆ Upload Artifacts to Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: frontend.tar.gz
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
